name: Trunk Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      
      - name: Install Trunk Toolchain
        uses: jetli/trunk-action@v0.5.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: trunk build --release --public-url learn_yew
      
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  
  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy Pages
        uses: actions/deploy-pages@v4
        id: deployment
